# Generated by Django 3.0.2 on 2022-01-27 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stream_bunny_v0_2_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=12, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=3, null=True)),
                ('poster_link', models.CharField(blank=True, max_length=280, null=True)),
                ('poster_low', models.CharField(blank=True, max_length=280, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1878), stream_bunny_v0_2_app.models.max_value_current_year])),
                ('director', models.CharField(max_length=100, null=True)),
                ('genres', models.CharField(max_length=100, null=True)),
                ('liked_by', models.ManyToManyField(related_name='liked_by', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='stream_bunny_v0_2_app.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='login_app.User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stream_bunny_v0_2_app.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
            ],
        ),
    ]
