# Generated by Django 2.2 on 2022-02-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_bunny_v0_2_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster_low',
            new_name='cast',
        ),
    ]
