# Generated by Django 2.2 on 2022-02-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_bunny_v0_2_app', '0002_auto_20220202_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='streaming_on',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
