# Generated by Django 2.2 on 2023-01-12 20:13

import django.core.validators
from django.db import migrations, models
import stream_bunny_v0_2_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_bunny_v0_2_app', '0003_auto_20220204_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1878), stream_bunny_v0_2_app.models.max_value_current_year]),
        ),
    ]
