# Generated by Django 2.2 on 2022-02-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20220208_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ticket',
            new_name='user',
        ),
    ]
